import { useState } from 'react';
import { useVaidyaStore } from '../store/chatStore';
import { niroApi } from '../services/api';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Loader2 } from 'lucide-react';
import vivekaImg from '../store/img/viveka.png';

const doshaOptions = ['Vata', 'Pitta', 'Kapha', 'Dual'] as const;
const herbOptions = [
  'Ashwagandha', 'Amla', 'Trikatu', 'Triphala', 
  'Shatavari', 'Brahmi', 'Guggulu', 'Arjuna',
  'Tulsi', 'Haritaki', 'Giloy'
];
const panchaOptions = [
  'Vamana (Emesis)',
  'Virechana (Purgation)',
  'Basti (Enema)',
  'Nasya (Nasal setup)',
  'Raktamokshana (Blood-letting)',
  'Shirodhara',
  'None'
];

export default function VaidyaVivekaPage() {
  const store = useVaidyaStore();
  const [loadingContext, setLoadingContext] = useState(false);
  const [loadingEval, setLoadingEval] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const loadCase = async () => {
    setLoadingContext(true);
    setErrorMsg('');
    store.setTeachingNote(null);
    try {
      let currentSessionId = store.sessionId;
      // Get a new session if none exists
      if (!currentSessionId) {
        const sessionRaw = await niroApi.createSession('VAIDYAVIVEKA');
        currentSessionId = sessionRaw.data.session.id;
        store.setSessionId(currentSessionId);
      }

      const response = await niroApi.sendMessage({
        sessionId: currentSessionId!,
        message: `new case difficulty: ${store.difficulty.toLowerCase()}`
      });

      const content = response.data.message.content;
      const caseMatch = content.match(/Case\sID:[^\n]+/i);
      const textMatch = content.match(/(?:Case:|Patient Details:)[\s\S]*?(?=\n\n|$)/i) || 
                        content.match(/(?:A \d+-year-old|A patient)[\s\S]*?(?=\n\n|$)/i);

      if (textMatch) {
         store.setLoadedCase({
           id: caseMatch ? caseMatch[0] : `case-${Date.now()}`,
           difficulty: store.difficulty,
           caseText: textMatch[0].replace(/Case:|Patient Details:/gi, '').trim()
         });
      } else {
         store.setLoadedCase({
           id: `case-${Date.now()}`,
           difficulty: store.difficulty,
           caseText: content
         });
      }
    } catch (err: any) {
      setErrorMsg('Failed to fetch a case. Please try again.');
    } finally {
      setLoadingContext(false);
    }
  };

  const evaluate = async () => {
    if (!store.loadedCase || !store.sessionId) {
      setErrorMsg('No active case session. Please Load Case first.');
      return;
    }
    setLoadingEval(true);
    setErrorMsg('');
    try {
      const response = await niroApi.sendMessage({
        sessionId: store.sessionId,
        message: `Evaluate case ${store.loadedCase.id}\nDosha: ${store.selectedDosha}\nHerb: ${store.selectedHerb}\nPanchakarma: ${store.selectedPanchakarma}`
      });

      store.setTeachingNote(response.data.message.content);
    } catch (err: any) {
      setErrorMsg('Failed to evaluate. Please check server connection.');
    } finally {
      setLoadingEval(false);
    }
  };

  const explainMistake = async () => {
    if (!store.loadedCase || !store.sessionId) {
       setErrorMsg('No active case session. Please Load Case first.');
       return;
    }
    setLoadingEval(true);
    setErrorMsg('');
    try {
      const response = await niroApi.sendMessage({
        sessionId: store.sessionId,
        message: `Explain my mistake case ${store.loadedCase.id}\nDosha: ${store.selectedDosha}\nHerb: ${store.selectedHerb}\nPanchakarma: ${store.selectedPanchakarma}`
      });

      store.setTeachingNote(response.data.message.content);
    } catch (err: any) {
      setErrorMsg('Failed to explain. Please check server connection.');
    } finally {
      setLoadingEval(false);
    }
  };

  return (
    <div className="main-content">
      <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        
        <div className="vaidya-hero-strip">
          <img src={vivekaImg} alt="VaidyaViveka" onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }} />
          <div>
            <h1 style={{ fontSize: '1.3rem', fontWeight: 800, margin: 0, color: '#fff' }}>VaidyaViveka</h1>
            <p style={{ fontSize: '0.85rem', margin: 0, opacity: 0.9 }}>AI-Guided Ayurvedic Clinical Reasoning</p>
          </div>
        </div>
        <p className="page-subtitle" style={{ margin: 0 }}>
          One case at a time — generated by Gemini/OpenAI (fallback cases included). No progress saved.
        </p>

        <hr style={{ borderColor: 'var(--border)', margin: '0.5rem 0' }} />

        <div className="text-secondary" style={{ fontSize: '0.9rem', lineHeight: 1.6 }}>
          <strong className="text-primary">How to use:</strong><br />
          1. Click <strong>Start / Load Case</strong> to generate a new case.<br />
          2. Read the vignette, choose dosha/herb/panchakarma.<br />
          3. Click <strong>Submit Diagnosis</strong> for instant feedback.<br />
          4. If unsure, click <strong>Explain My Mistake</strong> for a short AI teaching note.<br />
          5. Click <strong>Next Case</strong> to continue with another patient.<br /><br />
          <strong>Note:</strong> This app keeps cases only in memory for the current session, no progress is written to disk.
        </div>

        {errorMsg && (
          <div className="error-message">
            ⚠️ {errorMsg}
          </div>
        )}

        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div style={{ width: 'fit-content' }}>
            <div style={{ display: 'inline-block', background: 'var(--accent)', color: '#fff', padding: '2px 8px', borderRadius: 4, fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.5rem' }}>Select difficulty</div>
            <select 
              className="select"
              value={store.difficulty} 
              onChange={e => store.setDifficulty(e.target.value as any)}
            >
              <option value="Basic">Basic</option>
              <option value="Intermediate">Intermediate</option>
              <option value="Advanced">Advanced (Charaka Depth)</option>
            </select>
          </div>
        </div>

        <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
          <div style={{ background: 'var(--accent)', color: '#fff', padding: '4px 12px', fontSize: '0.85rem', fontWeight: 600, display: 'inline-block', margin: '12px 12px 0', borderRadius: 4 }}>
            Virtual Patient Case
          </div>
          <textarea
            readOnly
            className="form-input"
            value={store.loadedCase?.caseText || ''}
            style={{ width: '100%', height: '120px', border: 'none', background: 'transparent', padding: '12px', resize: 'none', boxShadow: 'none' }}
          />
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'minmax(250px, 1fr) 1fr 1fr', gap: '1rem' }}>
          <div>
            <div style={{ display: 'inline-block', background: 'var(--accent)', color: '#fff', padding: '2px 8px', borderRadius: 4, fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.5rem' }}>Select likely Dosha imbalance</div>
            <div style={{ display: 'flex', gap: '4px', background: 'var(--bg-secondary)', padding: '8px', borderRadius: 'var(--radius-sm)', flexWrap: 'wrap', border: '1px solid var(--border)' }}>
               {doshaOptions.map(o => {
                  const isSelected = store.selectedDosha === o;
                  return (
                    <button key={o} onClick={() => store.setSelectedDosha(o)}
                      style={{
                        background: isSelected ? 'var(--accent-bg)' : 'transparent',
                        color: isSelected ? 'var(--accent)' : 'var(--text-secondary)',
                        border: `1px solid ${isSelected ? 'var(--accent)' : 'transparent'}`,
                        padding: '4px 10px',
                        borderRadius: '20px',
                        fontSize: '0.85rem',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '6px',
                        cursor: 'pointer'
                      }}>
                      <div style={{ width: 12, height: 12, borderRadius: '50%', background: isSelected ? 'var(--accent)' : 'var(--bg-tertiary)', border: `2px solid ${isSelected ? 'transparent' : 'var(--border)'}` }} />
                      {o}
                    </button>
                  )
               })}
            </div>
          </div>
          <div>
            <div style={{ display: 'inline-block', background: 'var(--accent)', color: '#fff', padding: '2px 8px', borderRadius: 4, fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.5rem' }}>Select herbal remedy</div>
            <select 
              className="select"
              value={store.selectedHerb} 
              onChange={e => store.setSelectedHerb(e.target.value)}
            >
              <option value="" disabled>-- Select --</option>
              {herbOptions.map(o => <option key={o} value={o}>{o}</option>)}
            </select>
          </div>
          <div>
             <div style={{ display: 'inline-block', background: 'var(--accent)', color: '#fff', padding: '2px 8px', borderRadius: 4, fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.5rem' }}>Select Panchakarma treatment</div>
             <select 
              className="select"
              value={store.selectedPanchakarma} 
              onChange={e => store.setSelectedPanchakarma(e.target.value)}
            >
              <option value="" disabled>-- Select --</option>
              {panchaOptions.map(o => <option key={o} value={o}>{o}</option>)}
            </select>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginTop: '0.5rem' }}>
          <button onClick={() => void loadCase()} disabled={loadingContext} className="btn btn-secondary" style={{ flex: 1 }}>
            {loadingContext ? <Loader2 className="spin" size={20} /> : '🔄 Start / Load Case'}
          </button>
          <button onClick={() => void evaluate()} disabled={loadingEval || !store.loadedCase} className="btn btn-primary" style={{ flex: 1 }}>
            {loadingEval ? <Loader2 className="spin" size={20} /> : '✅ Submit Diagnosis'}
          </button>
          <button onClick={() => void explainMistake()} disabled={loadingEval || !store.loadedCase} className="btn btn-secondary" style={{ flex: 1 }}>
            🔎 Explain My Mistake (AI Tutor)
          </button>
          <button onClick={() => void loadCase()} disabled={loadingContext} className="btn btn-secondary" style={{ flex: 1 }}>
            ➡️ Next Case
          </button>
        </div>

        {store.teachingNote && (
          <div className="card" style={{ marginTop: '1rem' }}>
            <div className="message-content">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{store.teachingNote}</ReactMarkdown>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
